; Test.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 55.0
.source Test.java
.class public Test
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 5
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static main([Ljava/lang/String;)V
  .limit stack 1
  .limit locals 2
  .line 7
  0: iconst_5
  1: istore_1
  .line 8
  2: iconst_3
  3: istore_1
  .line 9
  4: return
.end method

